@DotnetApi_HostAddress = http://localhost:5208/api

GET {{DotnetApi_HostAddress}}/users/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IllZcC1uTm9adW5fLXZLMXF2YmFQdSJ9.eyJpc3MiOiJodHRwczovL2Rldi1kc2Fhczd1cmIyNzJsZHhjLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJVRlpuTUZmMUpTT3A2Q2JTRmJZekxPQTg3emFFSDhYckBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9kb3RuZXRhcGkuZ3JlbXkub3ZoIiwiaWF0IjoxNzMwMjc4NTg5LCJleHAiOjE3MzAzNjQ5ODksInNjb3BlIjoidXNlcjpydyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IlVGWm5NRmYxSlNPcDZDYlNGYll6TE9BODd6YUVIOFhyIiwicGVybWlzc2lvbnMiOlsidXNlcjpydyJdfQ.CJOB_tRPUWKsEOoAaJMlt-gtezqv3OCe9yWjEfnzNka03Ff4Ky_zAQu5hJLefAfADDk6qIHyWNpMLFpBk3Ktz7oQWk_d8esU55LljgmyPp1TJCLAli6p-_ugmhYWVbjPuRYQNJdzfhT0BtcP00992PC9xObDqoFIIPtChJQOZKd-MlZllb7WhQiCDoRhZCdyj0y1aiHvwJ195qw8PEAZvMC39_ZLWTYMq2EiHDUmCO3HuiD5MSAuWof3o6Voc2we8-6EykVjFJGOKFaAEu5IIC8v6lTR84bMh6VrqmKaR0o9qc5Jcl0-HLip6l1JSfL8Kle15O2ophkamTESzxBRbQ

###
